services:
  - type: web
    name: reminder-bot
    env: python
    plan: free
    branch: main
    autoDeploy: true
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: RENDER
        value: "true"
